# Generated by Django 4.0.5 on 2022-06-05 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ouser',
            new_name='owner',
        ),
    ]
