# Generated by Django 4.0.5 on 2022-06-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_app', '0002_alter_image_options_rename_ouser_profile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
