# Generated by Django 4.0.5 on 2022-06-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram_app', '0003_alter_image_image_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='media/profile/default.png', upload_to='profile/'),
        ),
    ]
