# Generated by Django 4.0.5 on 2022-06-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_app', '0008_alter_image_image'),
    ]

    operations = [
    ]
