# Generated by Django 4.0.5 on 2022-06-09 06:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram_app', '0010_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='profile/default.png', max_length=255, verbose_name='image'),
        ),
    ]
